name: Code Quality

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Sources/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Sources/**'

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Qlty Metrics
      uses: qltysh/qlty-action/cli@v2
      with:
        oidc: true